from src.quincy.base.NamelistTypes import *


def Generate_CTL_Categories(ctl_category):
    if ctl_category == NamelistCategories.ASSIMILATION_CTL:
        return ASSIMILATION_CTL()
    elif ctl_category == NamelistCategories.PHENOLOGY_CTL:
        return PHENOLOGY_CTL()
    elif ctl_category == NamelistCategories.VEGETATION_CTL:
        return VEGETATION_CTL()
    elif ctl_category == NamelistCategories.ATMLAND_CTL:
        return ATMLAND_CTL()
    elif ctl_category == NamelistCategories.RADIATION_CTL:
        return RADIATION_CTL()
    elif ctl_category == NamelistCategories.SHARED_CTL:
        return SHARED_CTL()
    elif ctl_category == NamelistCategories.SPQ_CTL:
        return SPQ_CTL()
    elif ctl_category == NamelistCategories.SB_CTL:
        return SB_CTL()
    else:
        print(f"Unknown CTL: {ctl_category}")
        return 0


class ASSIMILATION_CTL:
    def __init__(self):
        self.jmax2n  = NamelistItem(0.0)
        self.vcmax2n  = NamelistItem(0.0)
        self.pepc2n  = NamelistItem(0.0)
        self.chl2n  = NamelistItem(0.0)
        self.k1_fn_struc  = NamelistItem(0.0)
        self.E0kc  = NamelistItem(0.0)
        self.E1kc  = NamelistItem(0.0)
        self.E0ko  = NamelistItem(0.0)
        self.E1ko  = NamelistItem(0.0)
        self.E0pcp  = NamelistItem(0.0)
        self.E1pcp  = NamelistItem(0.0)
        self.E0v  = NamelistItem(0.0)
        self.E1v  = NamelistItem(0.0)
        self.t_jmax_offset  = NamelistItem(0.0)
        self.t_jmax_slope  = NamelistItem(0.0)
        self.t_jmax_opt_min  = NamelistItem(0.0)
        self.t_jmax_opt_max  = NamelistItem(0.0)
        self.Tref_pepc  = NamelistItem(0.0)
        self.Tbase_pepc  = NamelistItem(0.0)
        self.alpha_i  = NamelistItem(0.0)
        self.pO2  = NamelistItem(0.0)
        self.CiCa_default_C3 = NamelistItem(0.0)
        self.CiCa_default_C4=NamelistItem(0.0)
        self.ps_it_max=NamelistItem(0.0)
        self.ci_max=NamelistItem(0.0)
        self.Dwv2co2_air=NamelistItem(0.0)
        self.Dwv2co2_turb=NamelistItem(0.0)
        self.discr_ps_a_C13=NamelistItem(0.0)
        self.discr_ps_b_C13=NamelistItem(0.0)
        self.discr_ps_c_C13=NamelistItem(0.0)
        self.discr_ps_a_C14=NamelistItem(0.0)
        self.discr_ps_b_C14=NamelistItem(0.0)
        self.discr_ps_c_C14=NamelistItem(0.0)
        self.discr_ps_phi=NamelistItem(0.0)
        self.ka=NamelistItem(0.0)
        self.kn=NamelistItem(0.0)
        self.soa_b=NamelistItem(0.0)
        self.soa_t_s=NamelistItem(0.0)

class ATMLAND_CTL:
    def __init__(self):
        # No values here, yet
        dummy = 0

class PHENOLOGY_CTL:
    def __init__(self):
        # LAI at the site, used to set pheno:lai_max
        self.gdd_t_air_threshold = NamelistItem(0.0)
        
        
class RADIATION_CTL:
    def __init__(self):
        # No values here, yet
        self.kbl0_vis=NamelistItem(0.0)
        self.kdf0_vis=NamelistItem(0.0)
        self.kbl0_nir=NamelistItem(0.0)
        self.kdf0_nir=NamelistItem(0.0)
        self.rho2sbeta=NamelistItem(0.0)
        self.k_csf=NamelistItem(0.0)
        self.min_cos_zenith_angle_rad=NamelistItem(0.0)
        self.rad2ppfd=NamelistItem(0.0)
        
class SHARED_CTL:
    def __init__(self):
        self.mavg_period_weekly=NamelistItem(0.0)
        self.mavg_period_monthly=NamelistItem(0.0)
        self.mavg_period_yearly=NamelistItem(0.0)
        self.mavg_period_tsoa=NamelistItem(0.0)
        self.mavg_period_tuptake=NamelistItem(0.0)
        self.mavg_period_tlabile=NamelistItem(0.0)
        self.mavg_period_tphen=NamelistItem(0.0)
        self.mavg_period_tenzyme=NamelistItem(0.0)
        self.mavg_period_tresidual=NamelistItem(0.0)
        self.mavg_period_tfrac=NamelistItem(0.0)
        self.mavg_period_tcnl=NamelistItem(0.0)
        self.mavg_period_talloc=NamelistItem(0.0)
        self.mavg_period_talloc_dynamic=NamelistItem(0.0)
        self.mavg_period_tacclim=NamelistItem(0.0)
        self.mavg_period_tmic=NamelistItem(0.0)
        self.mavg_period_tgrowth=NamelistItem(0.0)
        self.mavg_period_tvegdyn=NamelistItem(0.0)
        
class SPQ_CTL:
    def __init__(self):
        self.soil_heat_cap=NamelistItem(0.0)
        self.soil_therm_cond=NamelistItem(0.0)
        self.InterceptionEfficiency=NamelistItem(0.0)
        self.w_skin_max=NamelistItem(0.0)
        self.drain_frac=NamelistItem(0.0)
        self.fdrain_srf_runoff=NamelistItem(0.0)
        self.height_wind=NamelistItem(0.0)
        self.wpot_pwp=NamelistItem(0.0)
        self.wpot_fc=NamelistItem(0.0)
        self.wpot_min=NamelistItem(0.0)
        self.k_pwp_a=NamelistItem(0.0)
        self.k_pwp_c=NamelistItem(0.0)
        self.k_pwp_s=NamelistItem(0.0)
        self.k_pwp_sc=NamelistItem(0.0)
        self.k_pwp_at=NamelistItem(0.0)
        self.k_pwp_bt=NamelistItem(0.0)
        self.k_fc_a=NamelistItem(0.0)
        self.k_fc_c=NamelistItem(0.0)
        self.k_fc_s=NamelistItem(0.0)
        self.k_fc_sc=NamelistItem(0.0)
        self.k_fc_at=NamelistItem(0.0)
        self.k_fc_bt=NamelistItem(0.0)
        self.k_fc_ct=NamelistItem(0.0)
        self.k_sat_a=NamelistItem(0.0)
        self.k_sat_c=NamelistItem(0.0)
        self.k_sat_s=NamelistItem(0.0)
        self.k_sat_sc=NamelistItem(0.0)
        self.k_sat_at=NamelistItem(0.0)
        self.k_sat_bt=NamelistItem(0.0)
        self.k_sat_ct=NamelistItem(0.0)
        self.k_sat_dt=NamelistItem(0.0)
        self.kdiff_sat_max=NamelistItem(0.0)
        self.f_psensi_soil_sand=NamelistItem(0.0)
        self.f_psensi_soil_silt=NamelistItem(0.0)
        self.f_psensi_soil_awc_prescribe=NamelistItem(0.0)
        self.f_psensi_bulk_density=NamelistItem(0.0)
        
        
class VEGETATION_CTL:
    def __init__(self):      
        self.fresp_growth=NamelistItem(0.0)
        self.fmaint_rate_base=NamelistItem(0.0)
        self.fmaint_rate_wood=NamelistItem(0.0)
        self.t_maint_k1=NamelistItem(0.0)
        self.t_maint_k2=NamelistItem(0.0)
        self.t_maint_k3=NamelistItem(0.0)
        self.f_resp_acclim=NamelistItem(0.0)
        self.t_acclim_zero=NamelistItem(0.0)
        self.k0_fn_pepc_C3=NamelistItem(0.0)
        self.k0_fn_pepc_C4=NamelistItem(0.0)
        self.jmax2vcmax_C3=NamelistItem(0.0)
        self.jmax2vcmax_C4=NamelistItem(0.0)
        self.tau_labile=NamelistItem(0.0)
        self.lambda_labile_temp=NamelistItem(0.0)
        self.k_labile_temp=NamelistItem(0.0)
        self.lambda_labile_theta=NamelistItem(0.0)
        self.k_labile_theta=NamelistItem(0.0)
        self.lambda_phiphen=NamelistItem(0.0)
        self.k_phiphen=NamelistItem(0.0)
        self.lambda_phimaint=NamelistItem(0.0)
        self.k_phimaint=NamelistItem(0.0)
        self.lambda_phimaint_nut=NamelistItem(0.0)
        self.k_phimaint_nut=NamelistItem(0.0)
        self.lambda_phistore=NamelistItem(0.0)
        self.k_phistore=NamelistItem(0.0)
        self.knut_labile=NamelistItem(0.0)
        self.lambda_sinklim_ps=NamelistItem(0.0)
        self.k_sinklim_ps=NamelistItem(0.0)
        self.k_cnp_sinklim_ps=NamelistItem(0.0)
        self.beta_sinklim_ps_min=NamelistItem(0.0)
        self.fstore_leaf_max=NamelistItem(0.0)
        self.fstore_fine_root_max=NamelistItem(0.0)
        self.fstore_sap_wood_max=NamelistItem(0.0)
        self.k_phi_interact=NamelistItem(0.0)
        self.resorp_fract_leaf=NamelistItem(0.0)
        self.resorp_fract_wood=NamelistItem(0.0)
        self.root2leaf_cn=NamelistItem(0.0)
        self.wood2leaf_cn=NamelistItem(0.0)
        self.root2leaf_np=NamelistItem(0.0)
        self.wood2leaf_np=NamelistItem(0.0)
        self.tau_nutrient_recycling=NamelistItem(0.0)
        self.kappa_f_demand_nc=NamelistItem(0.0)
        self.kappa_f_demand_pn=NamelistItem(0.0)
        self.k_f_demand=NamelistItem(0.0)
        self.k_cost_symb_bnf = NamelistItem(0.0)
        self.k1_temp_bnf=NamelistItem(0.0)
        self.k2_temp_bnf=NamelistItem(0.0)
        self.k3_temp_bnf=NamelistItem(0.0)
        self.k4_temp_bnf=NamelistItem(0.0)
        self.transform_cost_nh4=NamelistItem(0.0)
        self.transform_cost_no3=NamelistItem(0.0)
        self.transform_cost_org=NamelistItem(0.0)
        self.f_nacq_nh4=NamelistItem(0.0)
        self.f_nacq_no3=NamelistItem(0.0)
        self.vmax_symb_bnf=NamelistItem(0.0)
        self.km_symb_bnf=NamelistItem(0.0)
        self.eta_nfixation=NamelistItem(0.0)
        self.k0_fn_chl_C3=NamelistItem(0.0)
        self.k0_fn_chl_C4=NamelistItem(0.0)
        self.k1_fn_chl_C3=NamelistItem(0.0)
        self.k1_fn_chl_C4=NamelistItem(0.0)
        self.kfn_chl=NamelistItem(0.0)
        self.min_lai=NamelistItem(0.0)
        self.target_lai_max=NamelistItem(0.0)
        self.max_leaf_shedding_rate=NamelistItem(0.0)
        self.k_leafon_canopy=NamelistItem(0.0)
        self.background_mort_rate_tree=NamelistItem(0.0)
        self.background_mort_rate_grass=NamelistItem(0.0)
        self.lambda_mort_light=NamelistItem(0.0)
        self.k_mort_light=NamelistItem(0.0)
        self.lambda_est_temp=NamelistItem(0.0)
        self.k_est_temp=NamelistItem(0.0)
        self.lambda_est_moist=NamelistItem(0.0)
        self.k_est_moist=NamelistItem(0.0)
        self.k2_mort_greff=NamelistItem(0.0)
        self.k3_mort_greff=NamelistItem(0.0)
        self.min_greff=NamelistItem(0.0)
        self.max_crown_area=NamelistItem(0.0)
        self.min_diameter=NamelistItem(0.0)
        self.k_crown_area=NamelistItem(0.0)
        self.k_rp=NamelistItem(0.0)
        self.k_fpc=NamelistItem(0.0)
        self.fpc_max=NamelistItem(0.0)
        self.carbon_per_dryweight_leaf=NamelistItem(0.0)
        self.min_height=NamelistItem(0.0)
        self.sm2lm_grass=NamelistItem(0.0)
        self.lambda_fruit_alloc=NamelistItem(0.0)
        self.k1_fruit_alloc=NamelistItem(0.0)
        self.k3_fruit_alloc=NamelistItem(0.0)
        self.k4_fruit_alloc=NamelistItem(0.0)
        self.k1_root_alloc= NamelistItem(0.0)
        self.leaf2root_min_ratio=NamelistItem(0.0)
        self.leaf2root_max_ratio=NamelistItem(0.0)
        self.delta_n_fraction=NamelistItem(0.0)
        self.delta_n_leaf=NamelistItem(0.0)
        self.f_myc_exudation_max=NamelistItem(0.0)
        self.f_mycorrhization_max=NamelistItem(0.0)
        self.rfr_ratio_toc=NamelistItem(0.0)
        self.k_r2fr_chl=NamelistItem(0.0)
        
class SB_CTL:
    def __init__(self):
        self.tau_soluable_litter=NamelistItem(0.0)
        self.tau_metabolic_litter=NamelistItem(0.0)
        self.tau_structural_litter=NamelistItem(0.0)
        self.tau_woody_litter=NamelistItem(0.0)
        self.tau_fast=NamelistItem(0.0)
        self.tau_slow=NamelistItem(0.0)
        self.tau_biomineralisation=NamelistItem(0.0)
        self.temp_ref_tresponse=NamelistItem(0.0)
        self.ea_depolymerisation=NamelistItem(0.0)
        self.ea_mic_uptake=NamelistItem(0.0)
        self.ea_sorption=NamelistItem(0.0)
        self.ea_desorption=NamelistItem(0.0)
        self.ea_hsc=NamelistItem(0.0)
        self.ea_decomposition=NamelistItem(0.0)
        self.ed_decomposition=NamelistItem(0.0)
        self.t_ref_decomposition=NamelistItem(0.0)
        self.k1_afps=NamelistItem(0.0)
        self.k2_afps=NamelistItem(0.0)
        self.kmr_depolymerisation=NamelistItem(0.0)
        self.kmr_mic_uptake=NamelistItem(0.0)
        self.kmr_hsc=NamelistItem(0.0)
        self.kmr_sorption=NamelistItem(0.0)
        self.kmr_decomposition=NamelistItem(0.0)
        self.k_diff_org=NamelistItem(0.0)
        self.rho_bulk_org=NamelistItem(0.0)
        self.carbon_per_dryweight_SOM=NamelistItem(0.0)
        self.k_adsorpt_dom=NamelistItem(0.0)
        self.k_desorpt_dom=NamelistItem(0.0)
        self.k_adsorpt_det=NamelistItem(0.0)
        self.k_desorpt_det=NamelistItem(0.0)
        self.k_adsorpt_nh4=NamelistItem(0.0)
        self.k_desorpt_nh4=NamelistItem(0.0)
        self.k_adsorpt_po4=NamelistItem(0.0)
        self.k_desorpt_po4=NamelistItem(0.0)
        self.k_adsorpt_f_po4=NamelistItem(0.0)
        self.k_desorpt_f_po4=NamelistItem(0.0)
        self.microbial_cn=NamelistItem(0.0)
        self.microbial_np=NamelistItem(0.0)
        self.microbial_nue=NamelistItem(0.0)
        self.microbial_pue=NamelistItem(0.0)
        self.fc_woody2polymeric=NamelistItem(0.0)
        self.fc_soluable2dom=NamelistItem(0.0)
        self.microbial_cue=NamelistItem(0.0)
        self.microbial_cue_max=NamelistItem(0.0)
        self.microbial_cue_min=NamelistItem(0.0)
        self.frac_woody2dec_litter=NamelistItem(0.0)
        self.frac_litter2fast_som=NamelistItem(0.0)
        self.frac_fast2slow_som=NamelistItem(0.0)
        self.frac_slow2fast_som=NamelistItem(0.0)
        self.fc_woody2polymeric=NamelistItem(0.0)
        self.fc_soluable2dom=NamelistItem(0.0)
        self.k_mort_microbial=NamelistItem(0.0)
        self.min_mic_biomass=NamelistItem(0.0)
        self.vmax_mic_uptake=NamelistItem(0.0)
        self.km_mic_uptake=NamelistItem(0.0)
        self.km_depolymerisation=NamelistItem(0.0)
        self.vmax_depolymerisation_residue=NamelistItem(0.0)
        self.vmax_depolymerisation_litter=NamelistItem(0.0)
        self.f_soluable_residue=NamelistItem(0.0)
        self.f_soluable_leaf=NamelistItem(0.0)
        self.f_soluable_fine_root=NamelistItem(0.0)
        self.f_soluable_fruit=NamelistItem(0.0)
        self.f_soluable_seed_bed=NamelistItem(0.0)
        self.fc_soluable_max=NamelistItem(0.0)
        self.k_fc_soluable=NamelistItem(0.0)
        self.k_fn_soluable=NamelistItem(0.0)
        self.k_fp_soluable=NamelistItem(0.0)
        self.lc_leaf_max=NamelistItem(0.0)
        self.lc_leaf2sla=NamelistItem(0.0)
        self.lc_fine_root=NamelistItem(0.0)
        self.lc_coarse_root=NamelistItem(0.0)
        self.lc_woody_litter=NamelistItem(0.0)
        self.lc_fruit=NamelistItem(0.0)
        self.lc_seed_bed=NamelistItem(0.0)
        self.microbial_nue=NamelistItem(0.0)
        self.microbial_pue=NamelistItem(0.0)
        self.mycorrhiza_cue=NamelistItem(0.0)
        self.mycorrhiza_cn=NamelistItem(0.0)
        self.mycorrhiza_np=NamelistItem(0.0)
        self.f_maxresp_myc=NamelistItem(0.0)
        self.f_surface_myc2fineroot=NamelistItem(0.0)
        self.km1_up_nh4=NamelistItem(0.0)
        self.km2_up_nh4=NamelistItem(0.0)
        self.km1_up_no3=NamelistItem(0.0)
        self.km2_up_no3=NamelistItem(0.0)
        self.km1_up_po4=NamelistItem(0.0)
        self.km2_up_po4=NamelistItem(0.0)
        self.vmax_mic_uptake_nh4=NamelistItem(0.0)
        self.km_mic_uptake_nh4=NamelistItem(0.0)
        self.vmax_mic_uptake_no3=NamelistItem(0.0)
        self.km_mic_uptake_no3=NamelistItem(0.0)
        self.f_mic_carrier_n=NamelistItem(0.0)
        self.vmax_plant_uptake_nh4=NamelistItem(0.0)
        self.km_plant_uptake_nh4=NamelistItem(0.0)
        self.vmax_plant_uptake_no3=NamelistItem(0.0)
        self.km_plant_uptake_no3=NamelistItem(0.0)
        self.f_plant_carrier_n=NamelistItem(0.0)
        self.vmax_mic_uptake_po4=NamelistItem(0.0)
        self.km_mic_uptake_po4=NamelistItem(0.0)
        self.vmax_plant_uptake_po4=NamelistItem(0.0)
        self.km_plant_uptake_po4=NamelistItem(0.0)
        self.k_mic_uptake_nh4=NamelistItem(0.0)
        self.k_plant_uptake_nh4=NamelistItem(0.0)
        self.k_mic_uptake_no3=NamelistItem(0.0)
        self.k_plant_uptake_no3=NamelistItem(0.0)
        self.k_mic_uptake_po4=NamelistItem(0.0)
        self.k_plant_uptake_po4=NamelistItem(0.0)
        self.f_mic_carrier_po4=NamelistItem(0.0)
        self.f_plant_carrier_po4=NamelistItem(0.0)
        self.vmax_nitrification_nh4=NamelistItem(0.0)
        self.km_nitrification_nh4=NamelistItem(0.0)
        self.f_nit_carrier_nh4=NamelistItem(0.0)
        self.vmax_denitrification_no3=NamelistItem(0.0)
        self.km_denit_no3=NamelistItem(0.0)
        self.f_denit_carrier_no3=NamelistItem(0.0)
        self.qmax_po4_mineral=NamelistItem(0.0)
        self.qmax_nh4_clay=NamelistItem(0.0)
        self.km_adsorpt_mineral_po4=NamelistItem(0.0)
        self.km_adsorpt_OM_po4=NamelistItem(0.0)
        self.ea_nitrification=NamelistItem(0.0)
        self.ed_nitrification=NamelistItem(0.0)
        self.t_opt_nitrification=NamelistItem(0.0)
        self.f_nit_noy=NamelistItem(0.0)
        self.f_nit_n2o=NamelistItem(0.0)
        self.ea_denitrification=NamelistItem(0.0)
        self.vmax_nitrification=NamelistItem(0.0)
        self.vmax_denitrification=NamelistItem(0.0)
        self.km_denitrification_c=NamelistItem(0.0)
        self.km_denitrification_no3=NamelistItem(0.0)
        self.f_denit_noy=NamelistItem(0.0)
        self.f_denit_n2o=NamelistItem(0.0)
        self.ea_gasdiffusion=NamelistItem(0.0)
        self.lambda_anvf=NamelistItem(0.0)
        self.k_anvf=NamelistItem(0.0)
        self.floss_nmin=NamelistItem(0.0)
        self.fnit_nmin=NamelistItem(0.0)
        self.fleach_nh4=NamelistItem(0.0)
        self.fleach_po4=NamelistItem(0.0)
        self.km_asymb_bnf=NamelistItem(0.0)
        self.vmax_asymb_bnf=NamelistItem(0.0)
        self.eta_mic_uptake_nh4=NamelistItem(0.0)
        self.eta_mic_uptake_no3=NamelistItem(0.0)
        self.eta_plant_uptake_nh4=NamelistItem(0.0)
        self.eta_plant_uptake_no3=NamelistItem(0.0)
        self.eta_nitrification=NamelistItem(0.0)
        self.eta_nitrate_production=NamelistItem(0.0)
        self.eta_denitrification=NamelistItem(0.0)
        self.eta_ammonification=NamelistItem(0.0)
        self.eta_volatilisation_nh3=NamelistItem(0.0)
        self.k_weath_mineral=NamelistItem(0.0)
        self.eq_sorp_mineral_po4=NamelistItem(0.0)
        self.k_occlude_po4=NamelistItem(0.0)
        self.vmax_biochem_po4=NamelistItem(0.0)
        self.km_mic_biochem_po4=NamelistItem(0.0)
        self.km_dip_biochem_po4=NamelistItem(0.0)
        self.km_rootc_biochem_po4=NamelistItem(0.0)
        self.km_rootc_weath_po4=NamelistItem(0.0)
        self.km_root_enzyme_weath_po4=NamelistItem(0.0)
        self.biomin_threshold_pc_ratio_mic_res=NamelistItem(0.0)
        self.vmax_depolymerisation_residue=NamelistItem(0.0)
        self.vmax_depolymerisation_litter=NamelistItem(0.0)
        self.fc_p_res2dom=NamelistItem(0.0)
        self.fc_n_res2dom=NamelistItem(0.0)
        self.f_norg_limit=NamelistItem(0.0)
        self.f_tau_myc=NamelistItem(0.0)
        self.km_priming=NamelistItem(0.0)
        self.km_up_org=NamelistItem(0.0)
        self.myc_root_coverage_max=NamelistItem(0.0)
        self.resp_priming=NamelistItem(0.0)
        self.vmax_uptake_norg=NamelistItem(0.0)
        self.k_fast_som_cn_max=NamelistItem(0.0)
        self.k_fast_som_cn_min=NamelistItem(0.0)
        self.f_fast_som_cn=NamelistItem(0.0)
        self.k_slow_som_cn=NamelistItem(0.0)
        self.k_fast_som_np=NamelistItem(0.0)
        self.k_slow_som_np=NamelistItem(0.0)
        self.f_psensi_soil_p_depth=NamelistItem(0.0)
        self.f_psensi_soil_p_labile=NamelistItem(0.0)
        self.f_psensi_soil_p_slow=NamelistItem(0.0)
        self.f_psensi_soil_p_occluded=NamelistItem(0.0)
        self.f_psensi_soil_p_primary=NamelistItem(0.0)
        self.f_psensi_qmax_org_fine_particle=NamelistItem(0.0)  
        
class Paramlist:
    def __init__(self):
        # Initialise paramlist categories with defaults
        self.assimilation_ctl          = ASSIMILATION_CTL()
        self.atmland_ctl               = ATMLAND_CTL()
        self.phenology_ctl             = PHENOLOGY_CTL()
        self.radiation_ctl             = RADIATION_CTL()
        self.shared_ctl                = SHARED_CTL()
        self.spq_ctl                   = SPQ_CTL()
        self.vegetation_ctl            = VEGETATION_CTL()
        self.sb_ctl                    = SB_CTL()

    def check_if_parsed(self):
        for cat_str in vars(self):
            cat = getattr(self, cat_str)
            
            for var_str in vars(cat):
                item = getattr(cat, var_str)
                if not item.parsed:
                    print(f"Cat {cat}, var {var_str} has note been parsed")